---
name: halo
director_uuid: 8720c964-252d-41ed-8543-eb40b733a633

releases:
- name: cp
  version: 0+dev.63

networks:
- name: default
  type: dynamic
  cloud_properties:
    subnet: subnet-cf955197

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m3.medium
    availability_zone: us-west-1b
    auto_assign_public_ip: true

compilation:
  workers: 2
  network: default
  cloud_properties:
    availability_zone: us-west-1b
    instance_type: m3.medium

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: cp_halo
  templates:
  - name: cp_halo
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties:
    aws:
      access_key_id: AKIAIZLGLBCF7G6LQFCA # <--- Replace with AWS Access Key ID
      secret_access_key: 9+tOKHHKsk77GGkCVVN50nv7/uG72xZ1JURgzpom # <--- Replace with AWS Secret Key
      default_key_name: jlee
      default_security_groups: [jlee_bosh]
      region: us-west-1  # <--- Replace with Region

properties:
  cp_halo:
    agent_key: '422fb79572e214b83523f6fd56b8e898'
